### ISSUE TITLE
What is the compression format?

### ISSUE THREAD

**Issue by gis-geezer** [ArcGIS/tile-package-spec#1]
I'm looking to create my own tpkx. You have explained the structure of the tile package, but I could not see anywhere what the compression format is. Is it standard zip or something else?

Basically - once I have my file/directory structure, how do I create the tkpx file?

**Comment by gari0000** [comment]
@gis-geezer tilepackages use uncompressed store for archiving. You can use the following 7zip settings
![image](https://user-images.githubusercontent.com/38086909/99928059-6c94bd80-2cfc-11eb-8524-4ec914e6e8fb.png)

**Comment by gis-geezer** [comment]
Thanks – that’s the confirmation I needed.

**Comment by lucianpls** [comment]
This information should be added to the main page
